import { valid } from "semver";

import { renderCloudServiceInstall } from "./cloud-setup-install";
import { cloudServices, parseCloudSetup } from "./cloud-setup-schema";
import { renderCloudServiceStart } from "./cloud-setup-services";
import { nodeSelectorMatches } from "./toolchain-node";
import type { parseToolchainPolicy } from "./toolchain-schema";

export const cloudSetupPath = ".agents/cloud-setup.sh";
export const cloudEnvironmentMarker =
  "# Generated by stll-cloud-setup; disposable local test services.";

type GenerateCloudSetupOptions = {
  policy: ReturnType<typeof parseToolchainPolicy>;
  cloud: NonNullable<ReturnType<typeof parseCloudSetup>>;
  nodeVersion: string;
};

const script = String.raw`#!/usr/bin/env bash
# Generated by stll-cloud-setup. Regenerate with stll-cloud-setup.
# Networked installation and offline service startup are separate lifecycle steps.
# Cached filesystems may not preserve processes; run start at every session start.
# Supported platform: Ubuntu 24.04 (noble), amd64/arm64, root or passwordless sudo.
set -euo pipefail

usage() { echo 'Usage: cloud-setup.sh install|start' >&2; exit 2; }
[[ "$#" == 1 ]] || usage
case "$1" in install|start) MODE="$1" ;; *) usage ;; esac
fail() { echo "cloud-setup: $*" >&2; exit 1; }
trap 'echo "cloud-setup: command failed at line $LINENO" >&2' ERR
[[ -f /etc/os-release ]] || fail 'Ubuntu 24.04 is required'
. /etc/os-release
[[ "$ID" == ubuntu && "$VERSION_ID" == 24.04 && "$VERSION_CODENAME" == noble ]] || fail 'Only Ubuntu 24.04 (noble) is supported'
SCRIPT="$(realpath -- "$0")"
REPO_ROOT="$(cd -- "$(dirname -- "$SCRIPT")/.." && pwd -P)"
[[ "$SCRIPT" == "$REPO_ROOT/.agents/cloud-setup.sh" ]] || fail 'Run the generated repository script'
if [[ "$(id -u)" != 0 ]]; then
  command -v sudo >/dev/null && sudo -n true || fail 'Root or passwordless sudo is required'
  exec sudo -n -- bash "$SCRIPT" "$MODE"
fi
OUTPUT_UID="$(printenv SUDO_UID || id -u)"
[[ "$OUTPUT_UID" =~ ^[0-9]+$ ]] || fail 'Invalid invoking user'
OUTPUT_GID="$(getent passwd "$OUTPUT_UID" | cut -d: -f4)"
[[ "$OUTPUT_GID" =~ ^[0-9]+$ ]] || fail 'Invoking user is unavailable'
OUTPUT_USER="$(getent passwd "$OUTPUT_UID" | cut -d: -f1)"
OUTPUT_HOME="$(getent passwd "$OUTPUT_UID" | cut -d: -f6)"
[[ -n "$OUTPUT_USER" && "$OUTPUT_HOME" == /* && -d "$OUTPUT_HOME" ]] || fail 'Invoking user requires an existing home directory'
root() { "$@"; }
service_run() { runuser -u stll-cloud -- "$@" 9>&-; }
BUN_VERSION='@BUN@'
NODE_VERSION='@NODE@'
NODE_DIR="/opt/stll-cloud/node/$NODE_VERSION"
BUN_DIR="/opt/stll-cloud/bun/$BUN_VERSION"
export PATH="$NODE_DIR/bin:$BUN_DIR:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
BUN_CACHE="/var/cache/stll-cloud/bun/$OUTPUT_UID"
ENV_FILE=@ENV_FILE@
ENV_MARKER='@ENV_MARKER@'
[[ -f "$REPO_ROOT/.node-version" && ! -L "$REPO_ROOT/.node-version" ]] || fail 'A regular root .node-version is required'
[[ "$(awk 'NF { if (++count > 1 || NF != 1) exit 1; value=$1 } END { if (count != 1) exit 1; print value }' "$REPO_ROOT/.node-version")" == "$NODE_VERSION" ]] || fail 'Node selector changed; regenerate cloud-setup.sh'
cd -- "$REPO_ROOT"
case "$(uname -m)" in
  x86_64) ARCH=amd64; NODE_ARCH=x64; BUN_ARCH=x64 ;;
  aarch64|arm64) ARCH=arm64; NODE_ARCH=arm64; BUN_ARCH=aarch64 ;;
  *) fail 'Only amd64 and arm64 are supported' ;;
esac

runtime_ready() {
  [[ -x "$NODE_DIR/bin/node" && "$($NODE_DIR/bin/node --version)" == "v$NODE_VERSION" ]] || fail 'Pinned Node is unavailable; run install'
  [[ -x "$BUN_DIR/bun" && "$($BUN_DIR/bun --version)" == "$BUN_VERSION" ]] || fail 'Pinned Bun is unavailable; run install'
}
install_runtimes() {
  if ! command -v curl >/dev/null || ! command -v unzip >/dev/null || ! command -v xz >/dev/null || ! command -v openssl >/dev/null || ! command -v gpg >/dev/null; then
    apt-get update
    DEBIAN_FRONTEND=noninteractive apt_install ca-certificates curl unzip xz-utils openssl gnupg util-linux
  fi
  local scratch node_archive bun_archive bun_folder
  scratch="$(mktemp -d)"
  trap 'rm -rf -- "$scratch"' RETURN
  if [[ ! -x "$NODE_DIR/bin/node" ]] || [[ "$($NODE_DIR/bin/node --version)" != "v$NODE_VERSION" ]]; then
    node_archive="node-v$NODE_VERSION-linux-$NODE_ARCH.tar.xz"
    curl --fail --silent --show-error --location --proto '=https' --proto-redir '=https' --tlsv1.2 "https://nodejs.org/dist/v$NODE_VERSION/$node_archive" -o "$scratch/$node_archive"
    curl --fail --silent --show-error --location --proto '=https' --proto-redir '=https' --tlsv1.2 "https://nodejs.org/dist/v$NODE_VERSION/SHASUMS256.txt" -o "$scratch/node-sums"
    (cd "$scratch"; awk -v name="$node_archive" '$2 == name { print; count++ } END { if (count != 1) exit 1 }' node-sums | sha256sum --strict -c -)
    install -d -m 755 "$NODE_DIR"
    tar -xJf "$scratch/$node_archive" --strip-components=1 -C "$NODE_DIR"
  fi
  if [[ ! -x "$BUN_DIR/bun" ]] || [[ "$($BUN_DIR/bun --version)" != "$BUN_VERSION" ]]; then
    bun_folder="bun-linux-$BUN_ARCH"
    bun_archive="$bun_folder.zip"
    curl --fail --silent --show-error --location --proto '=https' --proto-redir '=https' --tlsv1.2 "https://github.com/oven-sh/bun/releases/download/bun-v$BUN_VERSION/$bun_archive" -o "$scratch/$bun_archive"
    curl --fail --silent --show-error --location --proto '=https' --proto-redir '=https' --tlsv1.2 "https://github.com/oven-sh/bun/releases/download/bun-v$BUN_VERSION/SHASUMS256.txt" -o "$scratch/bun-sums"
    (cd "$scratch"; awk -v name="$bun_archive" '$2 == name || $2 == "*" name { print $1 "  " name; count++ } END { if (count != 1) exit 1 }' bun-sums | sha256sum --strict -c -)
    unzip -q "$scratch/$bun_archive" -d "$scratch/bun"
    install -d -m 755 "$BUN_DIR"
    install -m 755 "$scratch/bun/$bun_folder/bun" "$BUN_DIR/bun"
  fi
  runtime_ready
  ln -sfnT -- "$NODE_DIR/bin/node" /usr/local/bin/node
  ln -sfnT -- "$NODE_DIR/bin/npm" /usr/local/bin/npm
  ln -sfnT -- "$NODE_DIR/bin/npx" /usr/local/bin/npx
  ln -sfnT -- "$BUN_DIR/bun" /usr/local/bin/bun
  rm -rf -- "$scratch"
  trap - RETURN
}

dependency_install() {
  local directory
  for directory in /var/cache/stll-cloud /var/cache/stll-cloud/bun; do
    [[ ! -L "$directory" ]] || fail 'Dependency cache parent must not be a symlink'
    if [[ -e "$directory" ]]; then
      [[ -d "$directory" && "$(stat -c '%u' "$directory")" == 0 ]] || fail 'Dependency cache parent must be root-owned'
    fi
    install -d -m 755 -o root -g root "$directory"
  done
  [[ ! -L "$BUN_CACHE" ]] || fail 'Dependency cache must not be a symlink'
  if [[ -e "$BUN_CACHE" ]]; then
    [[ -d "$BUN_CACHE" && "$(stat -c '%u' "$BUN_CACHE")" == "$OUTPUT_UID" ]] || fail 'Dependency cache ownership differs from the invoking user'
  fi
  install -d -m 700 -o "$OUTPUT_UID" -g "$OUTPUT_GID" "$BUN_CACHE"
  runuser -u "$OUTPUT_USER" -- env HOME="$OUTPUT_HOME" BUN_INSTALL_CACHE_DIR="$BUN_CACHE" PATH="$PATH" "$BUN_DIR/bun" install --frozen-lockfile
}

@SERVICE_INSTALL@
@SERVICE_START@

validate_environment() {
  local part target="$REPO_ROOT" env_path="$REPO_ROOT/$ENV_FILE" first_line temporary
  while IFS= read -r part; do
    target="$target/$part"
    [[ ! -L "$target" ]] || fail 'Environment path must not contain symbolic links'
  done < <(printf '%s\n' "$ENV_FILE" | tr '/' '\n')
  [[ -d "$(dirname -- "$env_path")" ]] || fail 'Environment parent directory is missing'
  if [[ -e "$env_path" ]]; then
    [[ -f "$env_path" ]] || fail 'Environment target must be a regular file'
    IFS= read -r first_line < "$env_path" || fail 'Refusing to overwrite an unowned environment file'
    [[ "$first_line" == "$ENV_MARKER" ]] || fail 'Refusing to overwrite an unowned environment file'
  fi
}
write_environment() {
  validate_environment
  local env_path="$REPO_ROOT/$ENV_FILE" temporary
  temporary="$(mktemp "$(dirname -- "$env_path")/.stll-cloud-env.XXXXXX")"
  chmod 600 "$temporary"
  {
    printf '%s\n' "$ENV_MARKER" 'NODE_ENV=test'
    if [[ -n "$DATABASE_URL" ]]; then printf 'DATABASE_URL=%s\n' "$DATABASE_URL"; fi
    if [[ -n "$REDIS_URL" ]]; then printf 'REDIS_URL=%s\n' "$REDIS_URL"; fi
  } > "$temporary"
  chown "$OUTPUT_UID:$OUTPUT_GID" "$temporary"
  mv -f -- "$temporary" "$env_path"
}

if [[ "$MODE" == install ]]; then
  install_runtimes
  install_services
  dependency_install
  exit 0
fi
runtime_ready
DATABASE_URL=''
REDIS_URL=''
validate_environment
prepare_state
start_services
write_environment
`;

const shellQuote = (value: string) => `'${value.replaceAll("'", "'\\''")}'`;

export const generateCloudSetup = ({
  policy,
  cloud,
  nodeVersion,
}: GenerateCloudSetupOptions) => {
  const selected = parseCloudSetup(cloud);
  if (selected === undefined) throw new Error("cloud declaration is required");
  const exactNode = nodeVersion.trim();
  if (
    valid(exactNode) !== exactNode ||
    !nodeSelectorMatches(exactNode, policy.node)
  )
    throw new Error(
      "cloud requires a tracked exact .node-version within the shared Node series",
    );
  const services = cloudServices.filter((service) =>
    selected.services.includes(service),
  );
  const replacements = new Map([
    ["@BUN@", policy.bun],
    ["@NODE@", exactNode],
    ["@ENV_FILE@", shellQuote(selected.envFile)],
    ["@ENV_MARKER@", cloudEnvironmentMarker],
    [
      "@SERVICE_INSTALL@",
      renderCloudServiceInstall({
        services,
        postgres: policy.postgres,
        valkey: policy.valkey,
        valkeyArtifacts: policy.valkeyArtifacts,
      }),
    ],
    [
      "@SERVICE_START@",
      renderCloudServiceStart({
        services,
        postgres: policy.postgres,
        valkey: policy.valkey,
      }),
    ],
  ]);
  return script.replace(/@[A-Z0-9_]+@/g, (token) => {
    const value = replacements.get(token);
    if (value === undefined)
      throw new Error(`Missing cloud setup field: ${token}`);
    return value;
  });
};
